<a href="https://colab.research.google.com/github/NikolaevaEV/PDA_SOL/blob/main/Homework_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Самостоятельная работа 2. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [2]:
import numpy as np
print (np.__version__)


1.23.5


2) Создать нулевой вектор размера 10

In [3]:
print (np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [4]:
print (np.full((7),7))

[7 7 7 7 7 7 7]


4) Создать вектор заполненный четными числами от 10 до 100

In [88]:
print (np.arange(10,102,2))

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [6]:
a = np.random.randint(0,100,10)
b = a[::-1]
print (a)
print (b)

[36 51 25 39 58 38 83 54 12 48]
[48 12 54 83 38 58 39 25 51 36]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [7]:
print (np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [74]:
print (np.eye(4,4, k=1))

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [45]:
a = np.diag(range(1,5))
a [a == 0] = 7
print (a)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [60]:
print (np.array(list(range(5)) * 5).reshape(5,5))

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [76]:
a = np.random.randint(10, size = (10, 10))
b = a - a.mean(axis = 1, keepdims = True)
print (a)
print (b)

[[8 4 1 2 8 2 5 2 0 0]
 [7 1 8 1 6 0 5 5 9 8]
 [8 2 5 9 8 7 5 8 2 7]
 [2 0 4 3 2 2 9 5 2 5]
 [5 1 2 2 8 2 1 0 3 4]
 [5 0 6 4 9 5 2 7 8 0]
 [2 6 0 1 9 6 4 6 4 7]
 [4 1 9 9 2 3 4 2 7 7]
 [2 7 8 6 1 4 8 0 3 3]
 [7 2 6 1 3 8 0 0 9 8]]
[[ 4.8  0.8 -2.2 -1.2  4.8 -1.2  1.8 -1.2 -3.2 -3.2]
 [ 2.  -4.   3.  -4.   1.  -5.   0.   0.   4.   3. ]
 [ 1.9 -4.1 -1.1  2.9  1.9  0.9 -1.1  1.9 -4.1  0.9]
 [-1.4 -3.4  0.6 -0.4 -1.4 -1.4  5.6  1.6 -1.4  1.6]
 [ 2.2 -1.8 -0.8 -0.8  5.2 -0.8 -1.8 -2.8  0.2  1.2]
 [ 0.4 -4.6  1.4 -0.6  4.4  0.4 -2.6  2.4  3.4 -4.6]
 [-2.5  1.5 -4.5 -3.5  4.5  1.5 -0.5  1.5 -0.5  2.5]
 [-0.8 -3.8  4.2  4.2 -2.8 -1.8 -0.8 -2.8  2.2  2.2]
 [-2.2  2.8  3.8  1.8 -3.2 -0.2  3.8 -4.2 -1.2 -1.2]
 [ 2.6 -2.4  1.6 -3.4 -1.4  3.6 -4.4 -4.4  4.6  3.6]]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [77]:
a = np.random.randint(10, size = (10,10))
b = a - np.median(a, axis = 0, keepdims = True)
print (a)
print (b)

[[7 8 7 2 4 5 5 7 5 9]
 [3 6 2 3 8 1 7 6 6 8]
 [5 0 8 6 5 4 7 6 4 3]
 [0 0 2 8 9 9 7 8 1 1]
 [1 5 7 6 3 3 7 8 2 0]
 [2 7 1 3 8 1 8 1 3 5]
 [2 4 3 1 1 0 5 8 4 4]
 [1 2 8 3 9 8 6 7 9 1]
 [9 9 7 9 3 4 1 6 7 4]
 [6 7 8 4 4 0 5 3 4 6]]
[[ 4.5  2.5  0.  -1.5 -0.5  1.5 -1.5  0.5  1.   5. ]
 [ 0.5  0.5 -5.  -0.5  3.5 -2.5  0.5 -0.5  2.   4. ]
 [ 2.5 -5.5  1.   2.5  0.5  0.5  0.5 -0.5  0.  -1. ]
 [-2.5 -5.5 -5.   4.5  4.5  5.5  0.5  1.5 -3.  -3. ]
 [-1.5 -0.5  0.   2.5 -1.5 -0.5  0.5  1.5 -2.  -4. ]
 [-0.5  1.5 -6.  -0.5  3.5 -2.5  1.5 -5.5 -1.   1. ]
 [-0.5 -1.5 -4.  -2.5 -3.5 -3.5 -1.5  1.5  0.   0. ]
 [-1.5 -3.5  1.  -0.5  4.5  4.5 -0.5  0.5  5.  -3. ]
 [ 6.5  3.5  0.   5.5 -1.5  0.5 -5.5 -0.5  3.   0. ]
 [ 3.5  1.5  1.   0.5 -0.5 -3.5 -1.5 -3.5  0.   2. ]]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [78]:
a = np.random.randint(10, size = (5,5))
a.max(axis = 1, keepdims = True)
a.min(axis = 1, keepdims = True)
print (np.concatenate((a, a.max(axis = 1, keepdims = True),a.min(axis = 1, keepdims = True)),axis = 1))

[[0 3 0 2 6 6 0]
 [8 4 3 1 3 8 1]
 [4 5 9 3 1 9 1]
 [8 1 3 1 7 8 1]
 [7 4 1 1 9 9 1]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [85]:
a = np.mat(np.arange(1,50)[1::2]).reshape(4,6)
b = np.mat(np.arange(1,50)[2::2]).reshape(6,4)
print (a)
print (b)
print (a*b)
print(np.linalg.inv(a*b))

[[ 2  4  6  8 10 12]
 [14 16 18 20 22 24]
 [26 28 30 32 34 36]
 [38 40 42 44 46 48]]
[[ 3  5  7  9]
 [11 13 15 17]
 [19 21 23 25]
 [27 29 31 33]
 [35 37 39 41]
 [43 45 47 49]]
[[1246 1330 1414 1498]
 [2902 3130 3358 3586]
 [4558 4930 5302 5674]
 [6214 6730 7246 7762]]
[[-3.66503876e+11  3.21853878e-04  1.09951163e+12 -7.33007752e+11]
 [-7.33007752e+11  2.19902326e+12 -2.19902326e+12  7.33007752e+11]
 [ 2.56552713e+12 -4.39804651e+12  1.09951163e+12  7.33007752e+11]
 [-1.46601550e+12  2.19902326e+12  0.00000000e+00 -7.33007752e+11]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [86]:
a = np.zeros((8,8), dtype=int)
a[1::2, ::2] = 1
a[::2, 1::2] = 1
print (a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
